version: '2.4'
services:
  taubsi:
    container_name: pokemon_taubsi
    build:
       context: ./Taubsi
    command: python3 start_taubsi.py
    restart: always
    volumes:
        - ./Taubsi/config/config.json:/usr/src/app/config.json
        - ./Taubsi/config/geofence.json:/usr/src/app/geofence.json
        - ./Taubsi/config/servers.json:/usr/src/app/servers.json
        - ./Taubsi/config/emotes.py:/usr/src/app/emotes.py
    depends_on:
        - rocketdb
    networks:
        - default
